### PR TITLE
Fix legacy authSecret and tlsSecret error

### LINKED ISSUE #522: legay tlsSecret and authSecret not working even without pulsarctl

### PR DESCRIPTION
**Pull request by jiangpengcheng**
Fixes #522 

### Motivation

should support legacy authSecret and tlsSecret

### Modifications

Fix legacy auth and tls support error

### Verifying this change

- [x] Make sure that the change passes the CI checks.

- [x] This change added tests and can be verified as follows:

  - *Added integration tests for pass tlsSecret and authSecret*

### Documentation

Check the box below.

Need to update docs? 

- [ ] `doc-required` 
  
  (If you need help on updating docs, create a doc issue)
  
- [x] `no-need-doc` 
  
  bug fix
  
- [ ] `doc` 
  
  (If this PR contains doc changes)

### CODE REVIEW

File: controllers/spec/common.go [hunk 1]
```diff
@@ -412,9 +412,7 @@ func getLegacyDownloadCommand(downloadPath, componentPackage string, tlsProvided
 		if tlsProvided {
 			args = append(args, []string{
 				"--tls-allow-insecure",
-				"${tlsAllowInsecureConnection:-" + DefaultForAllowInsecure + "}",
 				"--tls-enable-hostname-verification",
-				"${tlsHostnameVerificationEnable:-" + DefaultForEnableHostNameVerification + "}",
```
Comment (jiangpengcheng) [inline controllers/spec/common.go:417]: since `PulsarAdmin` doesn't support parameter in format: `--tls-allow-insecure true` but only support `--tls-allow-insecure` 

and the shell command will be very long if we judge the value of `tlsAllowInsecureConnection`, so we use hardcoded `--tls-allow-insecur` and `--tls-enable-hostname-verification` here

**Review by nlu90 — DISMISSED** [review]

**Review by freeznet — APPROVED** [review]
