### PR TITLE
Fix yaml format log config

### LINKED ISSUE #680: [bug] yaml format log config file doesn' twork
error is: `sh: bad substitution`

### PR DESCRIPTION
**Pull request by jiangpengcheng**
*(If this PR fixes a github issue, please add `Fixes #<xyz>`.)*

Fixes #680 

*(or if this PR is one task of a github issue, please add `Master Issue: #<xyz>` to link to the master issue.)*

Master Issue: #<xyz>

### Motivation

*Explain here the context, and why you're making that change. What is the problem you're trying to solve.*

### Modifications

*Describe the modifications you've done.*

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Documentation

Check the box below.

Need to update docs? 

- [ ] `doc-required` 
  
  (If you need help on updating docs, create a doc issue)
  
- [x] `no-need-doc` 
  
  (Please explain why)
  
- [ ] `doc` 
  
  (If this PR contains doc changes)

### CODE REVIEW

File: controllers/spec/common.go [hunk 1]
```diff
@@ -1072,7 +1072,7 @@ func getProcessJavaRuntimeArgs(name, packageName, clusterName, logLevel, details
 	state *v1alpha1.Stateful,
 	tlsConfig TLSConfig, authConfig *v1alpha1.AuthConfig,
 	maxPendingAsyncRequests *int32, logConfigFileName string) []string {
-	classPath := "/pulsar/instances/java-instance.jar"
+	classPath := "/pulsar/instances/java-instance.jar:/pulsar/lib/*"
```
Comment (jiangpengcheng) [inline controllers/spec/common.go:1075]: log4j yaml extensions requires some additional lib such as `com.fasterxml.jackson.core-jackson-databind-2.13.2.1.jar` and `com.fasterxml.jackson.dataformat-jackson-dataformat-yaml-2.13.2.jar`

File: controllers/spec/template/java-runtime-log4j.yaml.tmpl [hunk 2]
```diff
@@ -19,64 +19,62 @@ Configuration:
...
         SizeBasedTriggeringPolicy:
-          size: "100MB"
+          size: \"100MB\"
         {{ else }}
         TimeBasedTriggeringPolicy:
           interval: 1
           modulate: true
         SizeBasedTriggeringPolicy:
-          size: "10MB"
-        CronTriggeringPolicy:
```
Comment (jiangpengcheng) [inline controllers/spec/template/java-runtime-log4j.yaml.tmpl:63]: don't need `CronTriggeringPolicy` since we have a `TimeBasedTriggeringPolicy`

File: controllers/spec/template/java-runtime-log4j.yaml.tmpl [hunk 3]
```diff
@@ -19,64 +19,62 @@ Configuration:
...
       {{ else }}
       PatternLayout:
-        Pattern: "%d{ISO8601_OFFSET_DATE_TIME_HHMM} [%t] %-5level %logger{36} - %msg%n"
+        Pattern: \"%d{ISO8601_OFFSET_DATE_TIME_HHMM} [%t] %-5level %logger{36} - %msg%n\"
       {{ end }}
 
     RollingRandomAccessFile:
       name: RollingRandomAccessFile
-      fileName: "${sys:pulsar.function.log.dir}/${sys:pulsar.function.log.file}.log"
-      filePattern: "${sys:pulsar.function.log.dir}/${sys:pulsar.function.log.file}.%d{yyyy-MM-dd-hh-mm}-%i.log.gz"
```
Comment (jiangpengcheng) [inline controllers/spec/template/java-runtime-log4j.yaml.tmpl:28]: use `-mm` in file pattern and combine with `TimeBasedTriggeringPolicy` will result in rolling log file in every 1 minute

with `-hh` it will roll in every 1 hour, maybe we should use `yyyy-MM-dd` to roll the file log in every day?

Comment (freeznet) [reply controllers/spec/template/java-runtime-log4j.yaml.tmpl:28]: +1 to make it to `yyyy-MM-dd`.

**Review by freeznet — DISMISSED** [review]

File: controllers/spec/template/java-runtime-log4j.yaml.tmpl (hunk 3 above)
Comment (jiangpengcheng) [reply controllers/spec/template/java-runtime-log4j.yaml.tmpl:28]: updated

**Review by freeznet — APPROVED** [review]

**Review by nlu90 — APPROVED** [review]
